webtalk_init -webtalk_dir /home/lindelani/Documents/SCHOOL/EEE4120F/YODA/project/EEE4120F-YODA/EEE4120F-YODA.sim/sim_1/behav/xsim/xsim.dir/par_rand_gen_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun 22 19:57:20 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b46b25e0-4fd6-450c-9181-d4b522faacaf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9e54c04e75344711b192d292af1292b1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "172" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.005 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "29" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "160 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7130 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "177503" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2127" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "15.61_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "1265708_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1434981073 -regid "" -xml /home/lindelani/Documents/SCHOOL/EEE4120F/YODA/project/EEE4120F-YODA/EEE4120F-YODA.sim/sim_1/behav/xsim/xsim.dir/par_rand_gen_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/lindelani/Documents/SCHOOL/EEE4120F/YODA/project/EEE4120F-YODA/EEE4120F-YODA.sim/sim_1/behav/xsim/xsim.dir/par_rand_gen_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/lindelani/Documents/SCHOOL/EEE4120F/YODA/project/EEE4120F-YODA/EEE4120F-YODA.sim/sim_1/behav/xsim/xsim.dir/par_rand_gen_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
